### ISSUE TITLE
Research Web Frameworks that can be used for both Web and Phone

### ISSUE THREAD

**Issue by LTTien** [LTTien/BikingAround#1]
## Description
We need to have a framework that can translate between the web and as a phone app (phone friendly interface).

This might just be a framework that is web and mobile friendly
## Definition of Done
- [ ] Identify a framework that can be used for both mobile and web

## Tasks
- [ ] Research what frameworks are out there
- [ ] Find one that can be used for mobile as well as web

**Comment by LTTien** [comment]
Reference Meeting Notes: 
[1-11-20 Meeting 2](https://docs.google.com/document/d/1adIhnUqD2wU_qHr1NAH5SjKENrUu4-yWZjG5bAEopa0/edit?usp=sharing)
[1-18-20 Meeting 3](https://docs.google.com/document/d/128oddjpKfZOdCuCBR_cx0it9NAtMrObIqs6UEZwg_kg/edit?usp=sharing)
[1-25-20 Meeting 4](https://docs.google.com/document/d/1PJUJbfMperJpoA0po1vxT1d8BNhKqRKFbItDINTnAKQ/edit?usp=sharing)

_I will edit this later to include the actual discussions._

**Comment by zeucapua** [comment]
Solution: currently building with Flutter to start with mobile front end and eventually transitioning to Flutter for Web and/or switching to React for Web
