### ISSUE TITLE
First page for front-end

### ISSUE THREAD

**Issue by LTTien** [LTTien/BikingAround#3]
## Description
The Front end fat-finger first page into the github pages: https://lttien.github.io/PublicTransWebApp/
![MVIMG_20200125_111939](https://user-images.githubusercontent.com/12224777/73698201-4df20700-4695-11ea-8618-481542dfac56.jpg)

## Definition of Done
- [ ] Map 
- [ ] Upload to github pages for this repository

## Tasks
- [ ] use React <s>Native</s> for Web 
- [ ] navigation is on top for other dates (Link 1.. 5)
- [ ] side bar displays more bus info.

- [ ] <s>Make the map (google API) </s>-> moving this to a different Issue
- [ ] <s> Add the coordinates of 1 bus route </s>-> moving this to a different Issue
